# docker-compose.yml

version: "3.9"

services:
  hedge-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hedge-service
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    restart: unless-stopped